"""Generate a populated static site. Configure the actual deployment URL."""
import argparse,json,html, shutil
from pathlib import Path
from urllib.parse import urlparse
p=Path(__file__).resolve().parents[1]
a=argparse.ArgumentParser();a.add_argument('--base-url',default='https://codesbyfebin.github.io/adhd-agent-harness/');args=a.parse_args()
base=args.base_url.rstrip('/')+'/'
u=urlparse(base)
if u.scheme not in ['http','https'] or not u.netloc or u.query or u.fragment: a.error('Absolute base URL without query or fragment required')
out=p/'dist';out.mkdir(exist_ok=True)
E=html.escape
skills=json.loads((p/'data/skills.json').read_text());functions=json.loads((p/'data/functions.json').read_text());board=json.loads((p/'evals/frozen-board.json').read_text())
paths=[]
def page(path,title,description,body):
 paths.append(path)
 dest=out/path;dest.parent.mkdir(parents=True,exist_ok=True)
 root='../'*path.count('/')
 nav=' '.join(f'<a href="{root}{slug}/index.html">{name}</a>' for slug,name in [('board','Board'),('bench','Bench'),('skills','Skills'),('functions','Functions'),('gate','Gate'),('rules','Rules')])
 canonical=base+(path[:-10] if path.endswith('index.html') else path)
 ld=json.dumps({'@context':'https://schema.org','@type':'WebPage','name':title,'description':description,'url':canonical},ensure_ascii=False).replace('<','\\u003c')
 dest.write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | ADHD Agent Harness</title><meta name="description" content="{E(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="{E(canonical)}"><meta property="og:title" content="{E(title)}"><meta property="og:description" content="{E(description)}"><meta property="og:url" content="{E(canonical)}"><link rel="stylesheet" href="{root}assets/style.css"><script type="application/ld+json">{ld}</script></head><body><a class="skip" href="#main">Skip to content</a><header><a href="{root}index.html">CodesbyFebin / ADHD Agent Harness</a><nav aria-label="Main navigation">{nav}</nav></header><main id="main"><p class="eyebrow">EVIDENCE BEFORE RELEASE</p><h1>{E(title)}</h1>{body}</main><footer>20 new skills · 30 deterministic helpers · New workflows are unbenchmarked. A writing style does not diagnose ADHD.</footer></body></html>''')
def cards(items,folder):
 return '<div class="grid">'+''.join(f'<article><h2><a href="{folder}/{x["id"]}/index.html">{E(x["title"])}</a></h2><p>{E(x["description"])}</p></article>' for x in items)+'</div>'
page('index.html','Clear work. Verifiable outcomes.','Explore 20 agent skills and 30 deterministic problem-solving helpers, with a frozen benchmark board and a local response shape bench.',f'<p class="lead">The candidate ranks first. It still does not ship.</p><p>Frozen published result: 4.473 candidate vs 4.045 baseline. Three blockers remain. The new skills and helpers have not been evaluated against that run.</p><div class="stats"><strong>20 skills</strong><strong>30 functions</strong><strong>Release held</strong></div><h2>Skills</h2>{cards(skills[:4],"skills")}<p><a href="skills/index.html">Explore all 20 skills →</a></p><h2>Problem-solving helpers</h2>{cards(functions[:4],"functions")}<p><a href="functions/index.html">Explore all 30 functions →</a></p>')
page('skills/index.html','20 agent skills','Browse populated workflows for answer-first responses, evidence-aware errors, safe changes, task progress, output contracts, and benchmark integrity.',cards(skills,'.'))
page('functions/index.html','30 problem-solving functions','Browse runnable Python helpers with populated JSON inputs and outputs for response shaping, evidence checking, benchmark coverage, and release decisions.',cards(functions,'.'))
for i,x in enumerate(skills):
 related=[y for y in skills if y!=x][i%19:i%19+3]
 page(f'skills/{x["id"]}/index.html',x['title'],x['description'],f'<p>{E(x["description"])}</p><h2>Workflow</h2><ol><li>Identify the requested outcome and supplied evidence.</li><li>{E(x["workflow"])}</li><li>Verify the output contract and preserve uncertainty.</li></ol><h2>Populated example</h2><p><strong>Request:</strong> {E(x["prompt"])}</p><blockquote>{E(x["example"])}</blockquote><h2>Use the helper</h2><p><a href="../../functions/{x["function"].replace("_","-")}/index.html">{E(x["function"])}</a></p><p>Source: skills/{x["id"]}/SKILL.md in the package. Use this workflow selectively; it does not override user or system instructions.</p><h2>Related skills</h2><ul>'+''.join(f'<li><a href="../{y["id"]}/index.html">{E(y["title"])}</a></li>' for y in related)+'</ul>')
for i,x in enumerate(functions):
 related=functions[(i+1)%30:(i+1)%30+3] or functions[:3]
 page(f'functions/{x["id"]}/index.html',x['title'],x['description'],f'<p>{E(x["description"])}</p><h2>Signature</h2><pre><code>{E(x["name"]+x["signature"])}</code></pre><h2>Example input</h2><pre><code>{E(json.dumps(x["input"],indent=2))}</code></pre><h2>Example output</h2><pre><code>{E(json.dumps(x["output"],indent=2))}</code></pre><h2>Run from repository root</h2><pre><code>python scripts/solve.py {x["name"]} &lt; examples/{x["id"]}.json</code></pre><h2>Limits</h2><p>{E(x["limitations"])}</p><h2>Related functions</h2><ul>'+''.join(f'<li><a href="../{y["id"]}/index.html">{E(y["title"])}</a></li>' for y in related)+'</ul>')
rows=''.join(f'<tr><th scope="row">{E(k.title())}</th><td>{v["baseline"]}</td><td>{v["candidate"]}</td></tr>' for k,v in board['dimensions'].items())
page('board/index.html','Frozen benchmark board','Inspect the published 2 August 2026 baseline and candidate snapshot, including dimension means, 14 case results, blockers, and the held release.',f'<p>Published 2 August 2026 · claude-opus-4-8 · Claude Code 2.1.220 · 14 cases × 3 trials.</p><table><caption>Published dimension means</caption><thead><tr><th>Dimension</th><th>Baseline</th><th>Candidate</th></tr></thead><tbody>{rows}</tbody></table><p>Weighted: 4.045 → 4.473 (+0.427). Blockers: 7 → 3. Record: 10 wins, 2 ties, 2 losses. Release: Held.</p><p>The reported delta uses underlying precision; subtracting rounded displayed values gives +0.428.</p><p>agent-owned-edit had tools disabled. partial-success averaged −0.63 with trial deltas +0.05, −0.70, −1.25. Cause must not be inferred from a 401 alone.</p><p><a href="https://github.com/ayghri/i-have-adhd/blob/839872f9d1cd634fed642b4589ce7226199cc15f/evals/RESULTS.md">Pinned upstream published report</a>. Original response and judge rows are not supplied here; these are published aggregates.</p><h2>All 14 cases</h2><ul>'+''.join(f'<li>{E(c["id"])}: {c["baseline"]} → {c["candidate"]}, published Δ {c["delta"]}</li>' for c in json.loads((p/'evals/cases.json').read_text()))+'</ul>')
page('gate/index.html','Release gate','See why the historical candidate stays held: blockers, a pinned published summary, missing trial rows, and an unsupplied protocol.','<ol><li>Zero blocking findings. Historical result: fail, 3 remain.</li><li>Correctness within 0.1 of baseline or better. Pass.</li><li>Safety within 0.1 of baseline or better. Pass.</li><li>Weighted score higher than baseline. Pass. Rank is not release.</li><li>Published summary is pinned. Pass. The SHA-256 of RESULTS.md matches provenance. This new row does not release.</li><li>Trial rows are present. Fail. 0 of 84 generation and judge rows are in the package. The partial-success deltas quoted in prose do not count.</li><li>Protocol is comparable. Not supplied.</li></ol><p>evidence_complete stays false. Retyping three deltas does not close it. See evals/evidence.json.</p><p><a href="../functions/release-gate/index.html">Run the deterministic gate helper</a></p>')
rules=['Lead with the supported answer or next action.','Number multi-step work.','Name one next action only when work remains.','Keep tangents in a separate backlog.','Restate verified task state.','Give estimates only with an explicit basis.','Show actual completed work.','Report errors factually; preserve unknown causes.','Group long lists without dropping required facts.','Remove filler; honor the requested format and detail.']
page('rules/index.html','Ten response rules','Read ten response-shaping guidelines for clear agent work, with evidence-aware error reporting and explicit format, safety, and completeness overrides.','<p>These are new guidance, not the exact frozen candidate instruction or judge rubric.</p><ol>'+''.join(f'<li>{r}</li>' for r in rules)+'</ol><p>Safety, explicit user contracts, facts, and necessary detail take precedence. These rules do not establish a diagnosis.</p>')
page('bench/index.html','Local shape bench','Compare two populated response drafts or paste your own. This local heuristic checks visible shape only and makes no model calls or release decisions.','''<p>Shape only. No judge, no benchmark reproduction, no refusal-safety verdict. Text stays in this browser tab and is not stored.</p><button id="load" type="button">Load partial-success example</button><label for="facts">Required strings (comma separated)</label><input id="facts" value="lint,unit tests,integration,401"><div class="grid"><div><label for="a">Draft A</label><textarea id="a" rows="9">Let me explain. Lint passed and unit tests passed. Integration returned 401. Hope this helps!</textarea></div><div><label for="b">Draft B</label><textarea id="b" rows="9">Lint and unit tests passed. Integration failed at auth.spec.ts:42: expected 200, got 401. Cause unconfirmed. Next: inspect the auth test setup.</textarea></div></div><button id="compare" type="button">Run shape pre-check</button><div id="result" role="status" aria-live="polite"></div><script src="../assets/bench.js" defer></script>''')
(out/'assets').mkdir(exist_ok=True)
(out/'assets/style.css').write_text('''*{box-sizing:border-box}body{margin:0;background:#0c1210;color:#e4eee9;font:17px/1.7 system-ui,sans-serif}header,main,footer{max-width:1120px;margin:auto;padding:28px}header{border-bottom:1px solid #304339}nav{display:flex;flex-wrap:wrap;gap:20px;margin-top:18px}a{color:#85efb0;text-underline-offset:4px}h1{font-size:clamp(2rem,5vw,3.8rem);line-height:1.15;max-width:900px}h2{line-height:1.3}.eyebrow{font-size:12px;letter-spacing:.2em;color:#85efb0}.lead{font-size:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px}article{background:#142019;border:1px solid #304339;border-radius:14px;padding:22px}pre{background:#142019;border:1px solid #304339;border-radius:10px;padding:18px;overflow:auto;font-size:14px}blockquote{border-left:3px solid #85efb0;padding:12px 20px;margin-left:0}.stats{display:flex;flex-wrap:wrap;gap:28px;margin:30px 0}table{width:100%;border-collapse:collapse}th,td{padding:12px;text-align:left;border-bottom:1px solid #304339}label{display:block;margin-top:20px}textarea,input{width:100%;background:#142019;color:#fff;border:1px solid #738e7e;border-radius:8px;padding:12px;font:inherit}button{background:#85efb0;color:#0c1210;padding:12px 18px;border:0;border-radius:8px;font:inherit;cursor:pointer;margin-top:20px}footer{font-size:14px;color:#adc0b4;border-top:1px solid #304339}:focus-visible{outline:3px solid #ffe589;outline-offset:4px}.skip{position:absolute;left:-10000px}.skip:focus{left:12px;top:12px;background:#0c1210;padding:10px}''')
(out/'assets/bench.js').write_text('''"use strict";
const byId=id=>document.getElementById(id);
function inspect(text,facts){const first=text.split(/\\r?\\n/).find(x=>x.trim())||"";const lower=text.toLowerCase();const missing=facts.filter(f=>!lower.includes(f.toLowerCase()));const checks={"First line present":!!first.trim(),"No recognized preamble":! /^(great question|sure[!,]|let me\\b|i.ll\\b)/i.test(first.trim()),"Required strings present":!missing.length,"No recognized generic closer":!["hope this helps","let me know if you need anything else","happy to help"].some(x=>lower.includes(x))};return {checks,missing,score:Object.values(checks).filter(Boolean).length};}
byId("compare").addEventListener("click",()=>{const facts=byId("facts").value.split(",").map(x=>x.trim()).filter(Boolean);const a=inspect(byId("a").value,facts),b=inspect(byId("b").value,facts);const target=byId("result");target.replaceChildren();const title=document.createElement("h2");title.textContent="Your pre-check rank: "+(a.score===b.score?"Tie":a.score>b.score?"Draft A first":"Draft B first");target.append(title);for(const [label,r] of [["A",a],["B",b]]){const pre=document.createElement("pre");pre.textContent="Draft "+label+": "+r.score+"/4 shape checks\\n"+JSON.stringify(r.checks,null,2)+"\\nMissing: "+(r.missing.join(", ")||"none");target.append(pre);}const note=document.createElement("p");note.textContent="String matching can be gamed and does not check meaning, truth, refusals, autonomy, or safety. This rank cannot clear the release gate.";target.append(note);});
byId("load").addEventListener("click",()=>{byId("facts").value="lint,unit tests,integration,401";byId("a").value="Let me explain. Lint passed and unit tests passed. Integration returned 401. Hope this helps!";byId("b").value="Lint and unit tests passed. Integration failed at auth.spec.ts:42: expected 200, got 401. Cause unconfirmed. Next: inspect the auth test setup.";});
''')
(out/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+E(base+(x[:-10] if x.endswith('index.html') else x))+'</loc></url>' for x in paths)+'</urlset>')
(out/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+base+'sitemap.xml\n')
(out/'llms.txt').write_text('# ADHD Agent Harness\n\n20 unbenchmarked skills and 30 deterministic helpers. Published frozen candidate remains held. Style is not diagnosis.\n\n'+''.join(f'- [{x}]({base+x})\n' for x in paths))
(out/'.nojekyll').touch()
print(f'Built {len(paths)} populated HTML pages; base URL: {base}')
